name: CI

on:
  push:
    branches: [ master ]
  schedule:
    - cron: "0 0 * * 6"

jobs:
    compile:
        name: Build iso
        runs-on: ubuntu-latest
        steps:
          - name: Check out the repo
            uses: actions/checkout@v2
          - name: Run the build process with Docker
            uses: addnab/docker-run-action@v3
            with:
                image: debian:testing
                options: -v ${{ github.workspace }}:/root -v /output:/output
                run: |
                    cd /root
                    bash build.sh
                    mv *.iso /output/

          - uses: "marvinpinto/action-automatic-releases@latest"
            with:
                repo_token: "${{ secrets.GITHUB_TOKEN }}"
                automatic_release_tag: "current"
                prerelease: false
                title: "Latest release"
                files: |
                  /output/*


